/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.delibrary.api.spec;

import java.math.BigDecimal;
import com.delibrary.api.model.ErrorResponse;
import com.delibrary.api.model.IndividualModelRequest;
import com.delibrary.api.model.IndividualModelResponse;
import com.delibrary.api.model.ResponseMessage;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import javax.validation.constraints.*;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@Api(value = "individuals", description = "the individuals API")
public interface IndividualsApi {

    Logger log = LoggerFactory.getLogger(IndividualsApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Create new individual", nickname = "createIndividual", notes = "Create new individual", response = ResponseMessage.class, tags={ "Individual", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Operation", response = ResponseMessage.class),
        @ApiResponse(code = 400, message = "Invalid input data", response = ErrorResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 500, message = "Server Error") })
    @RequestMapping(value = "/individuals",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<ResponseMessage> createIndividual(@ApiParam(value = ""  )  @Valid @RequestBody IndividualModelRequest body) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"code\" : \"S01\",\n  \"meta\" : { },\n  \"description\" : \"Response Description\",\n  \"title\" : \"Response Message\"\n}", ResponseMessage.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default IndividualsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Delete existing individual", nickname = "deleteIndividual", notes = "Delete individual", response = ResponseMessage.class, tags={ "Individual", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Operation", response = ResponseMessage.class),
        @ApiResponse(code = 400, message = "Invalid input data", response = ErrorResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 500, message = "Server Error") })
    @RequestMapping(value = "/individuals/{id}/delete",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<ResponseMessage> deleteIndividual(@ApiParam(value = "Individual Id",required=true) @PathVariable("id") BigDecimal id) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"code\" : \"S01\",\n  \"meta\" : { },\n  \"description\" : \"Response Description\",\n  \"title\" : \"Response Message\"\n}", ResponseMessage.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default IndividualsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Get list of individual", nickname = "getAllIndividual", notes = "Get all information of individual in the company", response = IndividualModelResponse.class, tags={ "Individual", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Operation", response = IndividualModelResponse.class),
        @ApiResponse(code = 400, message = "Invalid input data", response = ErrorResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 500, message = "Server Error") })
    @RequestMapping(value = "/individuals",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    default ResponseEntity<IndividualModelResponse> getAllIndividual() {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"data\" : [ {\n    \"endpoint\" : [ \"EDIT\", \"EDIT\" ],\n    \"dob\" : \"2000-01-23\",\n    \"companyName\" : \"DeLi\",\n    \"name\" : \"name\",\n    \"id\" : 0.8008281904610115,\n    \"position\" : \"CTHDQT\"\n  }, {\n    \"endpoint\" : [ \"EDIT\", \"EDIT\" ],\n    \"dob\" : \"2000-01-23\",\n    \"companyName\" : \"DeLi\",\n    \"name\" : \"name\",\n    \"id\" : 0.8008281904610115,\n    \"position\" : \"CTHDQT\"\n  } ]\n}", IndividualModelResponse.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default IndividualsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }


    @ApiOperation(value = "Update existing individual", nickname = "updateIndividual", notes = "Update individual", response = ResponseMessage.class, tags={ "Individual", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Operation", response = ResponseMessage.class),
        @ApiResponse(code = 400, message = "Invalid input data", response = ErrorResponse.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 500, message = "Server Error") })
    @RequestMapping(value = "/individuals/{id}/edit",
        produces = { "application/json" }, 
        method = RequestMethod.PATCH)
    default ResponseEntity<ResponseMessage> updateIndividual(@ApiParam(value = "Individual Id",required=true) @PathVariable("id") BigDecimal id) {
        if(getObjectMapper().isPresent() && getAcceptHeader().isPresent()) {
            if (getAcceptHeader().get().contains("application/json")) {
                try {
                    return new ResponseEntity<>(getObjectMapper().get().readValue("{\n  \"code\" : \"S01\",\n  \"meta\" : { },\n  \"description\" : \"Response Description\",\n  \"title\" : \"Response Message\"\n}", ResponseMessage.class), HttpStatus.NOT_IMPLEMENTED);
                } catch (IOException e) {
                    log.error("Couldn't serialize response for content type application/json", e);
                    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
                }
            }
        } else {
            log.warn("ObjectMapper or HttpServletRequest not configured in default IndividualsApi interface so no example is generated");
        }
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }

}
